name: 'Update website'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.1.x

        - name: Run unit tests
          run: dotnet test

        - name: Generate website
          run: dotnet publish myapp.csproj --configuration Release

        - name: Publish website
          if: ${{ github.ref == 'refs/heads/master' }}
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: bin/Release/netstandard2.1/publish/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
            
        - name: Fix 404 page
          run: cp release/wwwroot/index.html release/wwwroot/404.html
