name: 'Update website'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 3.1.x

        - name: Run unit tests
          run: dotnet test

        - name: Generate website
          run: dotnet publish Portfolio/Portfolio.csproj --configuration Release --output build

        - name: Fix 404 page
          run: cp build/wwwroot/index.html build/wwwroot/404.html
          
        - name: Fix base tag
          run: sed -i 's/<base href="\/" \/>/<base href="\/Internship3\/" \/>/g' release/wwwroot/index.html
          
        - name: Fix Jekyll conflict
          run: touch build/wwwroot/.nojekyll

        - name: Publish website
          if: ${{ github.ref == 'refs/heads/master' }}
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BASE_BRANCH: master
            BRANCH: gh-pages
            FOLDER: build/wwwroot
            SINGLE_COMMIT: true
